<a href="https://colab.research.google.com/github/NoxFort1/fake-news-detector/blob/main/notebooks/01_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re

In [41]:
fake_df = pd.read_csv('Fake.csv')
true_df = pd.read_csv('True.csv')

In [42]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [43]:
fake_df.shape

(23481, 4)

In [44]:
fake_df.dtypes

title      object
text       object
subject    object
date       object
dtype: object

In [45]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [46]:
true_df.shape

(21417, 4)

In [47]:
true_df.dtypes

title      object
text       object
subject    object
date       object
dtype: object

In [48]:
fake_df['subject'].unique()

array(['News', 'politics', 'Government News', 'left-news', 'US_News',
       'Middle-east'], dtype=object)

In [49]:
true_df['subject'].unique()

array(['politicsNews', 'worldnews'], dtype=object)

In [50]:
fake_df = fake_df.drop(['subject', 'date'], axis = 1)
true_df = true_df.drop(['subject', 'date'], axis = 1)

In [51]:
def fix_split_contraction(text):
  text = re.sub(r"\b([A-Za-z]{2,})\s+n\s*t\b", r"\1n't", text, flags=re.IGNORECASE)
  text = re.sub(r"\b([A-Za-z]+)\s+(s|m|d|t|re|ve|ll)\b", r"\1'\2", text, flags=re.IGNORECASE)

  return text

In [52]:
WORD_RE = re.compile(r"(?:[A-Za-z]+|['’][A-Za-z]+)(?:['’][A-Za-z]+)*")

In [53]:
def count_words(text):
  text = ' '.join(text.split())
  text = fix_split_contraction(text)

  return len(WORD_RE.findall(text))

In [57]:
fake_df['words_in_title'] = fake_df['title'].apply(count_words)
fake_df['words_in_text'] = fake_df['text'].apply(count_words)
fake_df.head()

,title,text,words_in_title,words_in_text
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,12,470
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,8,308
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",15,592
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",14,456
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,11,420

In [58]:
true_df['words_in_title'] = true_df['title'].apply(count_words)
true_df['words_in_text'] = true_df['text'].apply(count_words)
true_df.head()

,title,text,words_in_title,words_in_text
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,11,738
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,10,620
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,11,456
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,10,378
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,11,840

In [68]:
print('FAKE ARTICLE')
print('Average amount of words in title: ', round(fake_df['words_in_title'].mean(), 2))
print('Average amount of words in text: ', round(fake_df['words_in_text'].mean(), 2))

FAKE ARTICLE
Average amount of words in title:  14.97
Average amount of words in text:  422.87

In [69]:
print('TRUE ARTICLE')
print('Average amount of words in title: ', round(true_df['words_in_title'].mean(), 2))
print('Average amount of words in text: ', round(true_df['words_in_text'].mean(), 2))

TRUE ARTICLE
Average amount of words in title:  10.2
Average amount of words in text:  382.72